### ISSUE TITLE
thermionic fabricator

### ISSUE THREAD

**Issue by archkazs** [gdarai/SpaceRace#12]
Hey, I was trying to make electrodes. I cannot make it work :/

It seems the recipe is not working somehow, I even place all the types of tin, it is not an oredictionary problem

![thermionic](https://user-images.githubusercontent.com/35575245/35480982-dcda4870-041a-11e8-9b78-2ec896f0b1ab.JPG)

**Comment by gdarai** [comment]
Yes... that is because you are using the old recipe... the correct ones are only the ones with Constantan in them. Shame the JEI is showing also the ol recipes even though they do not work.
