### ISSUE TITLE
Pipette doubling fluids

### ISSUE THREAD

**Issue by gdarai** [gdarai/SpaceRace#22]
People say that Pippette is doubling liquids in the forestry machines.
Explore and Decide what to do with it?

**Comment by OlorinCZ** [comment]
This only occured to me when the internal fluid tank was bugged, e.g. when changing fluids inside carpenter. Could it be this known issue, or is it something else altogether?

**Comment by gdarai** [comment]
I don't know. It didn't happen to me... but to other beta tester. And I wasn't able to reproduce. So for you it was on the bugged carpenter? I will try that. From what I know that is when you leave some fluid in it through save/load cycle. I am still not sure, if I want to solve things like that or just ignore it.

Like, solution is simple, remove pippette, but is it really neccessary? If it is just on the bugged carpenter... I will probably keep it. But if it will be more common issue, we will deal with it.

**Comment by gdarai** [comment]
Pipette was removed in 0.71
