### ISSUE TITLE
Chisel

### ISSUE THREAD

**Issue by gdarai** [gdarai/SpaceRace#7]
I am thinking about changing the chisel recipes... so those blocks would be cheaper to make... and could not be turned back to full scale blocks. What do you guys think?

**Comment by archkazs** [comment]
So far, I didn't use chisel. I don't have a house, just an open field :D

**Comment by OlorinCZ** [comment]
Yea, same with me. But out of curiosity, why would you like to disable the backward convertability? I thought that the point of the Chisel is that the blocks are interchangeable (and aside from chiseling vanilla blocks there are new pure decorative ones on top of that.)

**Comment by gdarai** [comment]
Well... I would keep the pure decorative ones... I just pity that nobody will ever se the blocks which are convertible from let's say gold block... They are nice but nobody will pay that.

So I thought that I would add a new receipt which would remove the gold block from this conversion list, make those blocks equivalent to let's say gold ingot, or couple of nuggets... and people would start using them.

Other possibility is to give the player opportunity to get ridiculous amount of gold somewhere... like from mining asteroids. That is also possible.

**Comment by gdarai** [comment]
Ok... so final decision was made by Storage Drawers... which just refuse to stop turning the Chiseled blocks into 9 ingots each... so unless I want to remove StorageDrawers the Blocks must be expensive. Sorry guys. No Chiseled Ships and ruins for you.
